# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
fastlane_require 'fastlane-plugin-firebase_app_distribution'

default_platform(:android)

platform :android do
    desc "Firebase CRUD"
    gradle(
        task: 'assemble',
        flags: "-Ptarget=lib/main.dart",
        build_type: 'Release',
        properties: {
            "android.injected.signing.store.file” => ENV[‘PWD’] + “/app/upload-keystore.jks",
            "android.injected.signing.store.password” => “uploadPassword",
            "android.injected.signing.key.alias” => “upload",
            "android.injected.signing.key.password” => “uploadPassword"
        }
    )

  lane :deploy do
      sh("flutter clean")
      sh("flutter pub get")
      sh("flutter build apk --release")
      firebase_app_distribution(
        app: "1:740980194646:android:36d8081903ba9cb50faaf7",
        groups: "Test",
        release_notes: "Add New Feature",
        firebase_cil_path: "/usr/local/bin/firebase",
        apk_path: "../build/app/outputs/flutter-apk/app-release.apk"
     )
  end
end
