default_platform(:android)


platform :android do
    desc "Runs all the tests"
    lane :test do
        gradle(task: "test")
    end

    desc "Submit a new Beta Build to Crashlytics Beta"
     lane :beta do
         gradle(task: "clean assembleRelease")
         crashlytics

     # sh "your_script.sh"
     # You can also use other beta testing services here
     end

    # Dev Release Lane
     desc "My awesome app"
     lane :distributeFirebase do
         sh("flutter clean")
         sh("flutter pub get")
         sh("flutter build apk --release")
         # build_android_app is a built-in fastlane action.
         firebase_app_distribution(
            app: "1:740980194646:android:36d8081903ba9cb50faaf7",
            groups: "test",
            release_notes: "First App release",
            android_artifact_type: "APK",
            android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
         )
     end
end
